version: '3.3'

services:
  admin:
    image: vtg-admin:latest
    build:
      context: .
    environment:
      - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_CMS_URL=${REACT_APP_CMS_URL}
      - REACT_APP_AUTH_URL=${REACT_APP_AUTH_URL}
    ports:
      - 8080:8080